### PR TITLE
Adding new positional weight script and example usage

### LINKED ISSUE #62: Add helper script to compute the mean position weights for a group of relays
This will help us to understand what fractional weights the relays in a PrivCount deployment have for a certain consensus or set of consensuses.

### PR DESCRIPTION
**Pull request by robgjansen**
closes #62

### CODE REVIEW

**Comment by robgjansen** [comment]
Do we want to include this eventually into the PrivCount tally server, so that the tally server runs this at the end of each collection phase and includes the results in the outcomes file? If so, that might be a longer term goal. But I could see if we don't even want this script in the privcount repo until then.

**Comment by robgjansen** [comment]
@teor2345 any thoughts on this? Do you think this script will be useful as part of PrivCount, or should I keep it separate for now?

Like I mentioned above, it would be nice if the TS could run this over all consensus files that were created during the measurement phase and include the results in the outcomes file, since otherwise that has to be a manual process. What do you think?

I'm happy to include the script now if you think it would be useful, but not add the feature where the TS runs it (if we decide we want that) until v0.3.0.

**Comment by teor2345** [comment]
I think it would be handy to have it in the repository, in case we want to run it manually for 0.2.0 data collections.

**Comment by robgjansen** [comment]
OK, great. Do you want to review it or should I just merge? (I understand this is less critical code since its not part of the main PrivCount base yet.)

**Comment by teor2345** [comment]
Review:
* Tools like atlas list family relay fingerprints with a leading $. This script should either remove the $, or warn when relay fingerprints aren't found.
* This script requires numpy and stem, so we should either:
  * move numpy from requirements-plot.txt to requirements.txt and add stem to requirements.txt, or
  * add another requirements-weights.txt file with numpy and stem.
  * Either way, we should update the README to list the new dependencies.
* Please make the file executable, so people can call it without using the interpreter (since that's what the #! at the start of the file suggests)

**Pull request merged**
